name: sa_deeplink_lego
description: "deep link dto template under simple architecture framework."
#publish_to: 'none'
repository: https://github.com/flutter-lego/sa_deeplink_lego

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  app_links:
  easy_event_bus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  widget_binding_lego: #@add
  sa_data_class_lego:
  sa_listener_lego:
  listener_lego:
  sa_app_links_listener_lego:
  app_links_lego:
  usage_note_lego:

flutter:
  assets:
    - assets/lego/sa_deeplink_lego/
  uses-material-design: true

topics:
  - lego